apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cicd
spec:
  selector:
    matchLabels:
      app: test-cicd
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-cicd
    spec:
      containers:
        - name: test-cicd
          image: "gcr.io/neural-guard-332812/tester"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi