apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      role: mongo
      environment: dev
  serviceName: "mongodb"
  replicas: 2
  template:
    metadata:
      labels:
        role: mongo
        environment: dev
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: monitoring-service-account
      containers:
      - name: mongo-service
        image: docker.io/mongo:4.2
        env:
        command: ["bin/sh"]
        args: ["-c", "mongod --replSet=rs0 --bind_ip_all"]
        ports:
        - name: mongo-port
          containerPort: 27017
        volumeMounts:
        - name: mongo-persistant-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistant-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi

